name: Scrape & Clean (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 6 * * *"   # 06:15 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check Scrapy is installed
        run: python -c "import sys, scrapy; print('Python:', sys.version); print('Scrapy:', scrapy.__version__)"

      - name: Run spider → raw_data.json
        run: python -m scrapy runspider src/spider.py -O data/raw_data.json -s FEED_EXPORT_ENCODING=utf-8

      - name: Clean data → cleaned_data.csv
        run: python src/cleaner.py

      - name: Commit & push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw_data.json data/cleaned_data.csv || true
          git commit -m "CI: update data" || echo "No changes to commit"
          git push